sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t gondov/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true gondov/react-test npm test

after_success:
  - docker build -t gondov/client ./client
  - docker build -t gondov/nginx ./nginx
  - docker build -t gondov/server ./server
  - docker build -t gondov/worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin



  - docker push gondov/client
  - docker push gondov/nginx
  - docker push gondov/server
  - docker push gondov/worker

