sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t agondov/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true agondov/react-test npm test

after_success:
  - docker build -t agondov/client ./client
  - docker build -t agondov/nginx ./nginx
  - docker build -t agondov/server ./server
  - docker build -t agondov/worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #- echo $DOCKER_PASSWORD | riff credential apply my-creds --set-default-image-prefix --docker-hub $DOCKER_ID


  - docker push agondov/client
  - docker push agondov/nginx
  - docker push agondov/cserver
  - docker push agondov/worker

